version: 2

models:
  - name: taxa_precipitacao_goes_16
    description: "Taxa de precipitação estimada de áreas do sudeste brasileiro. As estimativas são feitas de hora em hora, cada registro contendo dados desta estimativa. Cada área é um quadrado formado por 4km de lado. Dados coletados pelo satélite GOES-16."
    columns:
      - name: latitude
        description: "Latitude do centro da área."
      - name: longitude
        description: "Longitude do centro da área."
      - name: horario
        description: Horário de medição.
      - name: rrqpe
        description: "Taxa de precipitação estimada, medidas em milimetros por hora."


  - name: quantidade_agua_precipitavel_goes_16
    description: "Quantidade estimada de água precipitável na atmosfera de áreas do sudeste brasileiro. As estimativas são feitas de hora em hora, cada registro contendo dados desta estimativa. Cada área é um quadrado formado por 4km de lado. Dados coletados pelo satélite GOES-16."
    columns:
      - name: latitude
        description: "Latitude do centro da área."
      - name: longitude
        description: "Longitude do centro da área."
      - name: horario
        description: Horário de medição.
      - name: tpw
        description: "Quantidade total de água precipitável, medidas em milimetros."

  - name: infravermelho_longo_banda_13_goes_16
    description: "Medições da temperatura de brilho das nuvens e umidade utilizando o comprimento de onda de 10,3 µm do infravermelho (banda 13) na região da cidade do Rio de Janeiro. A unidade está em K. As estimativas são feitas a cada 10 minutos. Nome original: Clean Longwave IR Window Band."
    columns:
      - name: latitude
        description: "Latitude do centro da área."
      - name: longitude
        description: "Longitude do centro da área."
      - name: horario
        description: Horário de medição.
      - name: cmi
        description: "Temperatura de brilho da CMI (Cloud Moisture Imagery), medidas em K."
