version: 2

models:
  - name: meteorologia_inmet
    description: "Dados meteorológicos obtidas das estações do inmet ( Instituto Nacional de Meteorologia ) na cidade do Rio de Janeiro. As medidas são feitas de hora em hora, cada registro contendo dados destas medidas para cada estação. Entre os dados temos horário da medição, acumulado de chuva em 1 hora, direção e velocidade do vento, temperatura, pressão atmosférica, umidade e radiação global."
    columns:
      - name: id_estacao
        description: "ID da estação dada pelo INMET."
        tests:
          - unique
          - not_null
      - name: data
        description: "Data em que foi realizada a medição."
      - name: horario
        description: "Horário em que foi realizada a medição."
      - name: acumulado_chuva_1_h
        description: "Acumulado de chuva em 1 hora na estação em mm."
      - name: direcao_vento
        description: "Direção horária do vento na estação em º (gr)."
      - name: velocidade_vento
        description: "Velocidade do vento na estação em m/s."
      - name: rajada_vento_max
        description: "Rajada de vento máxima na estação em m/s."
      - name: pressao
        description: "Pressão atmosférica ao nível da estação em hPa."
      - name: pressao_minima
        description: "Pressão atmosférica mínima na hora anterior em hPa."
      - name: pressao_maxima
        description: "Pressão atmosférica máxima na hora anterior em hPa."
      - name: umidade
        description: "Umidade relativa do ar instantânea na estação em %."
      - name: umidade_minima
        description: "Umidade relativa mínima na hora anterior em %."
      - name: umidade_maxima
        description: "Umidade relativa máxima na hora anterior em %."
      - name: temperatura
        description: "Temperatura na medição instantânea na estação em ºC."
      - name: temperatura_minima
        description: "Temperatura mínima na hora anterior na estação em ºC."
      - name: temperatura_maxima
        description: "Temperatura máxima na hora anterior na estação em ºC."
      - name: radiacao_global
        description: "Radiação solar global captada na estação em KJ/m²."
      - name: temperatura_orvalho
        description: "Temperatura de orvalho instantânea na estação ºC."
      - name: temperatura_orvalho_minimo
        description: "Temperatura mínima de orvalho na hora anterior ºC."
      - name: temperatura_orvalho_maximo
        description: "Temperatura máxima de orvalho na hora anterior ºC."

  - name: meteorologia_inmet_temp
    description: "Dados meteorológicos obtidas das estações do inmet ( Instituto Nacional de Meteorologia ) na cidade do Rio de Janeiro. As medidas são feitas de hora em hora, cada registro contendo dados destas medidas para cada estação. Entre os dados temos horário da medição, acumulado de chuva em 1 hora, direção e velocidade do vento, temperatura, pressão atmosférica, umidade e radiação global."
    columns:
      - name: id_estacao
        description: "ID da estação dada pelo INMET."
        tests:
          - unique
          - not_null
      - name: data
        description: "Data em que foi realizada a medição."
      - name: horario
        description: "Horário em que foi realizada a medição."
      - name: acumulado_chuva_1_h
        description: "Acumulado de chuva em 1 hora na estação em mm."
      - name: direcao_vento
        description: "Direção horária do vento na estação em º (gr)."
      - name: velocidade_vento
        description: "Velocidade do vento na estação em m/s."
      - name: rajada_vento_max
        description: "Rajada de vento máxima na estação em m/s."
      - name: pressao
        description: "Pressão atmosférica ao nível da estação em hPa."
      - name: pressao_minima
        description: "Pressão atmosférica mínima na hora anterior em hPa."
      - name: pressao_maxima
        description: "Pressão atmosférica máxima na hora anterior em hPa."
      - name: umidade
        description: "Umidade relativa do ar instantânea na estação em %."
      - name: umidade_minima
        description: "Umidade relativa mínima na hora anterior em %."
      - name: umidade_maxima
        description: "Umidade relativa máxima na hora anterior em %."
      - name: temperatura
        description: "Temperatura na medição instantânea na estação em ºC."
      - name: temperatura_minima
        description: "Temperatura mínima na hora anterior na estação em ºC."
      - name: temperatura_maxima
        description: "Temperatura máxima na hora anterior na estação em ºC."
      - name: radiacao_global
        description: "Radiação solar global captada na estação em KJ/m²."
      - name: temperatura_orvalho
        description: "Temperatura de orvalho instantânea na estação ºC."
      - name: temperatura_orvalho_minimo
        description: "Temperatura mínima de orvalho na hora anterior ºC."
      - name: temperatura_orvalho_maximo
        description: "Temperatura máxima de orvalho na hora anterior ºC."

  - name: estacoes_inmet
    description: "Dados sobre as estações meteorológicas do inmet ( Instituto Nacional de Meteorologia ) na cidade do Rio de Janeiro."
    columns:
      - name: id_estacao
        description: "ID da estação definido pelo INMET."
        tests:
          - unique
          - not_null
      - name: estacao
        description: "Nome da estação."
      - name: sigla_uf
        description: "Sigla do estado."
      - name: id_municipio
        description: "Código do município do IBGE de 7 dígitos."
      - name: latitude
        description: "Latitude onde a estação se encontra."
      - name: longitude
        description: "Longitude onde a estação se encontra."
      - name: data_inicio_operacao
        description: "Data em que a estação começou a operar."
      - name: data_fim_operacao
        description: "Data em que a estação parou de operar."
      - name: situacao
        description: "Indica se a estação está operante ou com falha."
      - name: tipo_estacao
        description: "Indica se a estação é automática ou manual. Pode conter nulos."
      - name: entidade_responsavel
        description: "Entidade responsável pela estação."
      - name: data_atualizacao
        description: "Última data em que os dados sobre a data de operação foram atualizados."


  - name: estacoes_alertario
    description: "Dados sobre as estações pluviométricas do alertario ( Sistema Alerta Rio da Prefeitura do Rio de Janeiro ) na cidade do Rio de Janeiro."
    columns:
      - name: id_estacao
        description: "ID da estação definido pelo AlertaRIO."
        tests:
          - unique
          - not_null
      - name: estacao
        description: "Nome da estação."
      - name: latitude
        description: "Latitude onde a estação se encontra."
      - name: longitude
        description: "Longitude onde a estação se encontra."
      - name: cota
        description: "Altura em metros onde a estação se encontra."
      - name: x
        description: "X UTM (SAD69 Zona 23)"
      - name: y
        description: "Y UTM (SAD69 Zona 23)"
      - name: endereco
        description: "Endereço completo da estação."
      - name: situacao
        description: "Indica se a estação está operante ou com falha."
      - name: data_inicio_operacao
        description: "Data em que a estação começou a operar."
      - name: data_fim_operacao
        description: "Data em que a estação parou de operar."
      - name: data_atualizacao
        description: "Última data em que os dados sobre a data de operação foram atualizados."


  - name: estacoes_websirene
    description: "Dados sobre as estações pluviométricas do Sistema Alerta Sonoro da Prefeitura do Rio de Janeiro  (Websirene)."
    columns:
      - name: id_estacao
        description: "ID da estação definido pelo Websirene."
        tests:
          - unique
          - not_null
      - name: estacao
        description: "Nome da estação."
      - name: latitude
        description: "Latitude onde a estação se encontra."
      - name: longitude
        description: "Longitude onde a estação se encontra."


  - name: taxa_precipitacao_alertario
    description: "Taxa medida de precipitação das estações pluviométricas da cidade do Rio de Janeiro. As estimativas são feitas de 15 em 15 minutos, cada registro contendo dados desta medida."
    columns:
      - name: data_medicao
        description: "Data e horário em que foi realizada a medição"
      - name: id_estacao
        description: "ID da estação pluviométrica em que ocorreu a medição."
        tests:
          - unique
          - not_null
      - name: acumulado_chuva_15_min
        description: "Acumulado de chuva em 15 minutos."
      - name: acumulado_chuva_1_h
        description: "Acumulado de chuva em 1 hora."
      - name: acumulado_chuva_4_h
        description: "Acumulado de chuva em 4 horas."
      - name: acumulado_chuva_24_h
        description: "Acumulado de chuva em 24 horas."
      - name: acumulado_chuva_96_h
        description: "Acumulado de chuva em 96 horas."


  - name: taxa_precipitacao_satelite
    description: "Taxa de precipitação estimada de áreas do sudeste brasileiro. As estimativas são feitas de hora em hora, cada registro contendo dados desta estimativa. Cada área é um quadrado formado por 4km de lado. Dados coletados pelo satélite GOES-16."
    columns:
      - name: latitude
        description: "Latitude do centro da área."
      - name: longitude
        description: "Longitude do centro da área."
      - name: rrqpe
        description: "Taxa de precipitação estimada, medidas em milimetros por hora."


  - name: quantidade_agua_precipitavel_satelite
    description: "Quantidade estimada de água precipitável na atmosfera de áreas do sudeste brasileiro. As estimativas são feitas de hora em hora, cada registro contendo dados desta estimativa. Cada área é um quadrado formado por 4km de lado. Dados coletados pelo satélite GOES-16."
    columns:
      - name: latitude
        description: "Latitude do centro da área."
      - name: longitude
        description: "Longitude do centro da área."
      - name: tpw
        description: "Quantidade total de água precipitável, medidas em milimetros."
