version: 2

models:
  - name: eventos
    description: "**Descrição**: Eventos desde 2015. Um evento é uma ocorrência na\
      \ cidade do Rio de Janeiro que exija um acompanhamento e na maioria das vezes\
      \ uma ação da PCRJ. Por exemplo, Buraco na pista, bolsão d'água, enguiço mecânico.\
      \ Um evento aberto que não foi solucionado.\n**Frequência de atualização**:\
      \ Nunca\n**Cobertura temporal**: Não informado.\n**Órgão gestor dos dados**:\
      \ COR\n**Publicado por**: Patrícia Catandi\n**Publicado por (email)**: patriciabcatandi@gmail.com\n"
    columns:
      - name: evento_id
        description: "Identificador do evento."
        tests:
          - unique
          - not_null
      - name: inicio
        description: "Data e hora do registro do evento na PCRJ."
      - name: fim
        description: "Data e hora do encerramento do evento na PCRJ. O evento é encerrado quando é solucionado. Este atributo está vazio quanto o evento está aberto."
      - name: bairro
        description: "Bairro onde ocorreu o evento."
      - name: pop_id
        description: "Identificador do POP ( procedimento operacional padrão )."
      - name: status
        description: "Status do evento (ABERTO, FECHADO)."
      - name: gravidade
        description: "Gravidade do evento (BAIXO, MEDIO, ALTO, CRITICO)."
      - name: prazo
        description: "Prazo esperado de solução do evento (CURTO, MEDIO(acima de 3 dias), LONGO( acima de 5 dias))."
      - name: latitude
        description: "Latitude em formato WGS-84 em que ocorreu o evento."
      - name: longitude
        description: "Longitude em formato WGS-84 em que ocorreu o evento"
      - name: informe_id
        description: "Atributo não utilizado."
      - name: descricao
        description: "Descrição do evento."


  - name: atividades_eventos
    description: "**Descrição**: Atividades estão sendo executadas ou que foram executadas.\n\
      **Frequência de atualização**: Nunca\n**Cobertura temporal**: Não informado.\n\
      **Órgão gestor dos dados**: COR\n**Publicado por**: Patrícia Catandi\n**Publicado\
      \ por (email)**: patriciabcatandi@gmail.com\n"
    columns:
      - name: evento_id
        description: "Identificador do evento."
      - name: inicio
        description: "Data e hora do registro do evento na PCRJ."
      - name: fim
        description: "Data e hora do encerramento do evento na PCRJ. O evento é encerrado quando é solucionado. Este atributo está vazio quanto o evento está aberto."
      - name: chegada
        description: "Data e hora da chegada da atividade."
      - name: sigla
        description: "Sigla do orgão que está realizando ou realizou a atividade."
      - name: status
        description: "Status do evento (ABERTO, FECHADO)."

  - name: atividades_orgaos_responsaveis_pop
    description: "**Descrição**: Atividades que compõem os POPs.\n**Frequência de\
      \ atualização**: Nunca\n**Cobertura temporal**: Não informado.\n**Órgão gestor\
      \ dos dados**: COR\n**Publicado por**: Patrícia Catandi\n**Publicado por (email)**:\
      \ patriciabcatandi@gmail.com\n"
    columns:
      - name: pop_titulo
        description: "Nome da POP ao qual a atividade está ligada."
      - name: sigla
        description: "Sigla do órgão responsável pela atividade."
      - name: orgao
        description: "Orgão responsável pela atividade."
      - name: acao
        description: "Descrição da atividade."


  - name: procedimento_operacional_padrao
    description: "**Descrição**: Procedimentos operacionais padrões (POP) existentes\
      \ na PCRJ.  Procedimento que será usado para solucionar o evento.Um POP é composto\
      \ de várias atividades.\n**Frequência de atualização**: Nunca\n**Cobertura temporal**:\
      \ Não informado.\n**Órgão gestor dos dados**: COR\n**Publicado por**: Patrícia\
      \ Catandi\n**Publicado por (email)**: patriciabcatandi@gmail.com\n"
    columns:
      - name: pop_titulo
        description: "Nome da POP ao qual a atividade está ligada."
      - name: pop_id
        description: "Identificador do POP procedimento operacional padrão)."
